services:
  uplite:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - SQLALCHEMY_DATABASE_URI=postgresql://uplite:uplite_password@postgres:5432/uplite
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./src/uplite/static/images/connections:/app/src/uplite/static/images/connections
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=uplite
      - POSTGRES_USER=uplite
      - POSTGRES_PASSWORD=uplite_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: uplite_network
